image: openjdk:16-alpine3.13

stages:
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build-via-gradle:
  stage: build
  script:
    - echo "Ensuring application is able to be compiled..."
    - ./gradlew compileJava compileKotlin
    - echo "Compilation tests completed!"

create-jar:
  stage: build
  script:
    - ./gradlew shadowJar
  artifacts:
    paths:
      - build/libs/*.jar

deploy-to-internal:
  only:
    refs:
      - main
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_INTERNAL_REGISTRY_PASS" | docker login $DOCKER_INTERNAL_REGISTRY --username $DOCKER_INTERNAL_REGISTRY_USER --password-stdin
  script:
    - docker build -t docker-registry.omnicron.dev/server-manager .
    - docker push docker-registry.omnicron.dev/server-manager:latest
    - docker push docker-registry.omnicron.dev/server-manager:v1

deploy-to-dockerhub:
  only:
    refs:
      - main
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login $DOCKER_HUB_IMAGE --username $DOCKER_HUB_USERNAME --password-stdin
  script:
    - docker build -t $DOCKER_HUB_IMAGE .
    - docker push $DOCKER_HUB_IMAGE:latest
    - docker push $DOCKER_HUB_IMAGE:v1
    - docker push $DOCKER_HUB_IMAGE:$CI_COMMIT_SHA
