image: openjdk:16-alpine3.13

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build-via-gradle:
  stage: build
  script:
    - echo "Ensuring application is able to be compiled..."
    - ./gradlew compileJava compileKotlin
    - echo "Compilation tests completed!"

create-jar:
  stage: build
  script:
    - ./gradlew shadowJar
  artifacts:
    paths:
      - build/libs/*.jar

deploy-to-docker:
  only:
    refs:
      - main
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login $DOCKER_REGISTRY --username $DOCKER_REGISTRY_USER --password-stdin
  script:
    - docker build -t docker-registry.omnicron.dev/server-manager .
    - docker push docker-registry.omnicron.dev/server-manager:latest
